---
display:
  preview:
    margin: 4
  pum:
    y_max_len: 16
    x_max_len: 66
    y_ratio: 0.3
    x_margin: 16
    ellipsis: …

    kind_context:
      - " ["
      - "]"
    source_context:
      - "「"
      - "」"

  mark_highlight_group: Pmenu

match:
  unifying_chars:
    - _
    - "-"

  exact_matches: 2
  fuzzy_cutoff: 0.6
  context_lines: 20

  timeout: 0.1
  manual_timeout: 0.5

weights:
  prefix_matches: 2.0
  consecutive_matches: 1.5
  insertion_order: 1.0
  match_density: 1.0
  neighbours: 1.0
  num_matches: 1.0
  count_by_filetype: 0.5

keymap:
  recommended: True
  manual_complete: <c-space>
  jump_to_mark: <c-space>

clients:
  tabnine:
    enabled: False
    short_name: "T9"
    bin: null
    tie_breaker: -10

  tmux:
    enabled: True
    short_name: "TMUX"
    match_syms: False
    polling_interval: 1.0
    tie_breaker: 10

  buffers:
    enabled: True
    short_name: "BUF"
    match_syms: False
    tie_breaker: 20

  tree_sitter:
    enabled: False
    short_name: "TS"
    tie_breaker: 30

  paths:
    enabled: True
    short_name: "FILE"
    tie_breaker: 40

  snippets:
    enabled: True
    short_name: "SNIP"
    tie_breaker: 50

  tags:
    enabled: True
    short_name: "TAG"
    match_syms: True
    polling_interval: 1.0
    path_sep: " ⇉ "
    parent_scope: " ⇊"
    tie_breaker: 60

  lsp:
    enabled: True
    short_name: "LSP"
    tie_breaker: 70

