---
display:
  ellipsis: …
  margin: 16
  max_len: 66

match:
  unifying_chars:
    - _
    - "-"
  timeout: 0.1
  transpose_band: 3

weights:
  prefix_matches: 1.0
  consecutive_matches: 1.0
  insertion_order: 1.0
  match_density: 1.0
  nearest_neighbour: 1.0
  num_matches: 1.0
  count_by_filetype: 1.0

keymap:
  prev_mark: <C-p>
  next_mark: <C-n>

clients:
  tree_sitter:
    enabled: True
    short_name: "TS"
    weight: 1.0
  lsp:
    enabled: True
    short_name: "LSP"
    weight: 1.0
  buffers:
    enabled: True
    short_name: "BUF"
    weight: 1.0
  paths:
    enabled: True
    short_name: "FILE"
    weight: 1.0
  snippets:
    enabled: True
    short_name: "SNIP"
    weight: 1.0
  tmux:
    enabled: True
    short_name: "TMUX"
    weight: 1.0
    polling_interval: 1.0

