---
display:
  ellipsis: …
  pum:
    y_max_len: 16
    x_max_len: 66
    y_ratio: 0.3
    x_margin: 16

  mark_highlight_group: Pmenu

match:
  unifying_chars:
    - _
    - "-"
  timeout: 0.1
  manual_timeout: 0.5
  transpose_band: 3

weights:
  prefix_matches: 2.0
  consecutive_matches: 1.5
  insertion_order: 1.0
  match_density: 1.0
  nearest_neighbour: 0.5
  num_matches: 1.0
  count_by_filetype: 0.5

keymap:
  recommended: True
  manual_complete: <c-space>
  jump_to_mark: <c-space>

clients:
  tree_sitter:
    enabled: True
    short_name: "TS"
    priority: 3
  lsp:
    enabled: True
    short_name: "LSP"
    priority: 4
  buffers:
    enabled: True
    short_name: "BUF"
    match_syms: False
    priority: 1
  paths:
    enabled: True
    short_name: "FILE"
    priority: 5
  snippets:
    enabled: True
    short_name: "SNIP"
    priority: 2
  tmux:
    enabled: True
    short_name: "TMUX"
    priority: 0
    match_syms: False
    polling_interval: 1.0

