---
limits:
  idle_time: 2.0
  max_buf_index: 99999

display:
  preview:
    y_margin: 2
    x_margin: 4
    x_max_len: 88
    lsp_timeout: 0.05
  pum:
    y_max_len: 16
    x_max_len: 66
    y_ratio: 0.3
    ellipsis: …

    kind_context:
      - " ["
      - "]"
    source_context:
      - "「"
      - "」"

  mark_highlight_group: Pmenu

match:
  unifying_chars:
    - _
    - "-"

  exact_matches: 2
  fuzzy_cutoff: 0.6
  context_lines: 20

  timeout: 0.1
  manual_timeout: 0.5

weights:
  prefix_matches: 2.0
  consecutive_matches: 2.0
  insertion_order: 2.0
  neighbours: 1.0
  num_matches: 1.0

keymap:
  recommended: True

  manual_complete: <c-space>
  bigger_preview: <c-k>
  jump_to_mark: <c-h>

clients:
  tabnine:
    enabled: False
    short_name: "T9"
    limit: 6
    tie_breaker: -10

  tmux:
    enabled: True
    short_name: "TMUX"
    match_syms: False
    limit: 66
    tie_breaker: 10

  buffers:
    enabled: True
    short_name: "BUF"
    match_syms: False
    same_filetype: False
    limit: 66
    tie_breaker: 20

  tree_sitter:
    enabled: True
    short_name: "TS"
    limit: 66
    tie_breaker: 30

  paths:
    enabled: True
    short_name: "FILE"
    limit: 66
    tie_breaker: 40

  snippets:
    enabled: True
    short_name: "SNIP"
    limit: 66
    tie_breaker: 50

  tags:
    enabled: True
    short_name: "TAG"
    limit: 66
    match_syms: True
    path_sep: " ⇉ "
    parent_scope: " ⇊"
    tie_breaker: 60

  lsp:
    enabled: True
    short_name: "LSP"
    limit: 66
    tie_breaker: 70

