---
keymap:
  recommended: True

  manual_complete: <c-space>
  bigger_preview: <c-k>
  jump_to_mark: <c-h>

match:
  unifying_chars:
    - "_"
    - "-"
  max_results: 33
  proximate_lines: 16
  exact_matches: 2
  look_ahead: 2
  fuzzy_cutoff: 0.6

weights:
  prefix_matches: 2.0
  edit_distance: 1.5
  recency: 1.0
  proximity: 0.5

display:
  pum:
    y_max_len: 16
    y_ratio: 0.3

    x_max_len: 66
    x_min_len: 9

    ellipsis: …
    kind_context:
      - " ["
      - "]"
    source_context:
      - "「"
      - "」"

  preview:
    x_max_len: 88
    lsp_timeout: 0.06
    positions:
      north: 1
      south: 2
      west: 3
      east: 4

  mark_highlight_group: Pmenu

limits:
  index_cutoff: 333333
  idle_time: 2.0
  timeout: 0.088
  manual_timeout: 0.6

  download_retries: 6
  download_timeout: 66.0

clients:
  tabnine:
    enabled: False
    short_name: "T9"
    tie_breaker: -16

  tmux:
    enabled: True
    short_name: "TMUX"
    match_syms: False
    tie_breaker: 06

  buffers:
    enabled: True
    short_name: "BUF"
    match_syms: False
    same_filetype: False
    tie_breaker: 16

  tree_sitter:
    enabled: True
    short_name: "TS"
    tie_breaker: 26

  paths:
    enabled: True
    short_name: "PATH"
    tie_breaker: 36
    preview_lines: 6

  snippets:
    enabled: True
    short_name: "SNIP"
    tie_breaker: 46
    sources: []

  tags:
    enabled: True
    short_name: "TAG"
    match_syms: True
    path_sep: " ⇉ "
    parent_scope: " ⇊"
    tie_breaker: 56

  lsp:
    enabled: True
    short_name: "LSP"
    tie_breaker: 66
    always_request: False
