---
display:
  ellipsis: …
  margin: 16
  max_len: 66
  mark_highlight_group: Pmenu

match:
  unifying_chars:
    - _
    - "-"
  timeout: 0.1
  manual_timeout: 0.5
  transpose_band: 3

weights:
  prefix_matches: 2.0
  consecutive_matches: 1.5
  insertion_order: 1.0
  match_density: 1.0
  nearest_neighbour: 0.5
  num_matches: 1.0
  count_by_filetype: 0.5

keymap:
  recommended: True
  jump_to_mark: <C-space>

clients:
  tree_sitter:
    enabled: True
    short_name: "TS"
    weight: 1.0
  lsp:
    enabled: True
    short_name: "LSP"
    weight: 1.0
  buffers:
    enabled: True
    short_name: "BUF"
    match_syms: False
    weight: 1.0
  paths:
    enabled: True
    short_name: "FILE"
    weight: 1.0
  snippets:
    enabled: True
    short_name: "SNIP"
    weight: 1.0
  tmux:
    enabled: True
    short_name: "TMUX"
    weight: 1.0
    match_syms: False
    polling_interval: 1.0

