---
display:
  ellipsis: …
  pum_max_len: 66

match:
  unifying_chars:
    - _
    - "-"
  timeout: 0.1
  transpose_band: 3

weights:
  alphabetical: 1.0
  consecutive_matches: 1.0
  count_by_filetype: 1.0
  insertion_order: 1.0
  nearest_neighbour: 1.0
  num_matches: 1.0
  prefix_matches: 1.0

clients:
  tree_sitter:
    short_name: "TS"
    weight: 1.5
  lsp:
    short_name: "LS"
    weight: 1.5
  buffers:
    short_name: "B"
    weight: 1.0
    prefix_length: 2
  paths:
    short_name: "F"
    weight: 2.0
  tmux:
    short_name: "TMX"
    weight: 1.0
    prefix_length: 2

