---
display:
  ellipsis: …
  pum_max_len: 66

match:
  unifying_chars:
    - _
    - "-"
  timeout: 0.1
  transpose_band: 3

weights:
  alphabetical: 1.0
  consecutive_matches: 1.0
  count_by_filetype: 1.0
  insertion_order: 1.0
  nearest_neighbour: 1.0
  num_matches: 1.0
  prefix_matches: 1.0

clients: {}

