---
sources:
  lsp:
    - https://github.com/vue-vscode-snippets/snippets
    - https://github.com/vscode-angular-snippets/snippets
    - https://github.com/vscode-es7-javascript-react-snippets/snippets
    - https://github.com/vscode-react/snippets
    - https://github.com/rocketseat-vscode-react-native-snippets/snippets
    - https://github.com/snipsnap/snippets
    - https://github.com/vscode-javascript/snippets
    - https://github.com/vscode-R/snippets
  neosnippet:
    - https://github.com/neosnippet-snippets/neosnippets
  snipmate:
    - https://github.com/vim-snippets/snippets
    - https://github.com/vim-go/gosnippets/snippets
  ultisnips:
    - https://github.com/vim-snippets/UltiSnips
    - https://github.com/vim-go/gosnippets/UltiSnips

