---
sources:
  snu:
    - https://github.com/honza/vim-snippets
    - https://github.com/Shougo/neosnippet-snippets
    - https://github.com/fatih/vim-go
    - https://github.com/snipsnapdev/snipsnap
  lsp:
    - https://github.com/sdras/vue-vscode-snippets
    - https://github.com/johnpapa/vscode-angular-snippets
    - https://github.com/dsznajder/vscode-es7-javascript-react-snippets
    - https://github.com/xabikos/vscode-react
    - https://github.com/Rocketseat/rocketseat-vscode-react-native-snippets
    - https://github.com/xabikos/vscode-javascript
    - https://github.com/Ikuyadeu/vscode-R

