---
name: CI

on:
  push:
  schedule:
    - cron: "0 0 * * *" # daily

jobs:
  mypy:
    strategy:
      matrix:
        python_ver:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
          - "3"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python_ver }}

      - name: Apt Packages
        run: |-
          sudo -- apt install --yes -- universal-ctags

      - name: Codespell
        run: |-
          pip3 install -- codespell
          codespell --skip ./artifacts/helo.yml --skip ./tests/shared/fuzzy.py

      - name: Lint
        run: make lint

      - name: Install
        run: python3 -m coq deps

      - name: Test
        run: python3 -m tests
